version: 1.0.0.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
- ps: dotnet pack -c Release Wox.Plugin.MyWoxPlugin/Wox.Plugin.MyWoxPlugin.csproj

after_build:
- ps: >-
    Compress-Archive -Path "Wox.Plugin.MyWoxPlugin\bin\Release\net452\*" -DestinationPath "plugin.zip"

    Rename-Item plugin.zip Wox.Plugin.MyWoxPlugin.wox

artifacts:
    - path: 'Wox.Plugin.MyWoxPlugin.wox'